version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres 
    environment:
      DATABASE_URL: ************
      NODE_ENV: development
      PORT: 3000
    ports: 
      - "3000:3000"
    command: npm run docker
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:12.1
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postg$$$$$$res
      POSTGRES_PASSWORD: $$$$$$$$$$$
      POSTGRES_DB: NCnews
    